# ===================================================================
# PERFIL DE PRODUCCIÓN (PROD)
# ===================================================================
# La URL usa las variables de entorno para el Host y Nombre de la BD
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=UTC
# 'validate' es la única opción segura para producción
spring.jpa.hibernate.ddl-auto=validate
# Desactivamos los logs ruidosos de SQL en producción
spring.jpa.show-sql=false
logging.level.org.flywaydb=INFO
logging.level.org.hibernate.SQL=WARN