spring.application.name=Titta API

# ===================================================================
# PUERTO DE LA APLICACIÓN
# ===================================================================
server.port=8080

# ===================================================================
# CONFIGURACIÓN DE LA BASE DE DATOS (MySQL)
# ===================================================================
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:db_titta}?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=${BD_DRIVER}

# ===================================================================
# CONFIGURACIÓN DE JPA (Hibernate)
# ===================================================================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ===================================================================
# CONFIGURACIÓN DE FLYWAY
# ===================================================================
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration
spring.flyway.enabled=true
logging.level.org.flywaydb=debug

# ===================================================================
# CONFIGURACIÓN DE SPRINGDOC (SWAGGER UI)
# ===================================================================
# Agrupa todas las APIs bajo el prefijo /api/v1
springdoc.paths-to-match=/api/v1/**

# Información que aparecerá en la cabecera de Swagger UI
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.display-request-duration=true
# Necesario en Spring Boot 3+ para que el matching de prefijos funcione bien
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# Información personalizada de la API
info.app.name=API REST
info.app.description=Proyecto de ecommerce Titta
info.app.version=0.0.1


