name: Java CI con Maven

on:
  push:
    branches: [ "main", "master", "develop" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest



    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'

    - name: Iniciar Redis con Contraseña
      run: |
        docker run -d -p 6379:6379 --name redis redis:alpine redis-server --requirepass secret
        sleep 5

    - name: Ejecutar Tests con Maven
      run: chmod +x mvnw && ./mvnw test -Dspring.profiles.active=test -B

    - name: Publicar Reporte de Tests
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: target/surefire-reports
